apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-argocd-dev
  namespace: flask-argocd
  labels:
    app: flask-app-argocd
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: flask-app-argocd
        env:
        - name: ENVIRONMENT
          value: dev