apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-argocd
  namespace: flask-argocd
spec:
  template:
    spec:
      containers:
      - name: flask-app-argocd
        env:
        - name: ENVIRONMENT
          value: dev