apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: truongphamxuan/flask-docker
  newName: truongphamxuan/flask-docker
  newTag: 9885ae1

patchesStrategicMerge:
- deployment-patch.yaml
