apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: truongphamxuan/flask-docker
  newName: truongphamxuan/flask-docker
  newTag: b3637d67d5b366587fd9e2222a8126ce91f2d189

patchesStrategicMerge:
- deployment-patch.yaml
