apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-argocd-prod
spec:
  template:
    spec:
      containers:
      - name: flask-app-argocd-prod
        env:
        - name: ENVIRONMENT
          value: prod