apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-argocd
  labels:
    app: flask-app-argocd
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: flask-app-argocd
        env:
        - name: ENVIRONMENT
          value: prod