apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: truongphamxuan/flask-docker
    newTag: c141d9a

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

resources:
  - ../../base