apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: truongphamxuan/flask-docker
    newTag: c8d0ed0

patchesStrategicMerge:
  - deployment-patch.yaml

resources:
  - ../../base