apiVersion: v1
kind: Service
metadata:
  name: flask-service-argocd
spec:
  ports:
    - protocol: TCP
      port: 5000 #Service port
      targetPort: 5000 #The port for the React.js application container
      nodePort: 32224